### ISSUE TITLE
[GUI] Autocomplete is Broken

### ISSUE THREAD

**Issue by MTrop** [MTrop/DoomTools#89]
I'm guessing this started happening after the upgrade to RSyntaxTextArea 3.3.2. Trying to open AutoComplete creates an NPE:
```
[2023-01-25 11:23:02.134] (DoomToolsGUIMain) ERROR: Thread [AWT-EventQueue-0] threw an uncaught exception!
java.lang.NullPointerException: Cannot invoke "java.net.URL.toExternalForm()" because "location" is null
	at java.desktop/javax.swing.ImageIcon.<init>(ImageIcon.java:234)
	at org.fife.ui.autocomplete.AutoCompleteDescWindow$ToolBarBackAction.<init>(AutoCompleteDescWindow.java:588)
	at org.fife.ui.autocomplete.AutoCompleteDescWindow.<init>(AutoCompleteDescWindow.java:158)
	at org.fife.ui.autocomplete.AutoCompletePopupWindow.createDescriptionWindow(AutoCompletePopupWindow.java:216)
	at org.fife.ui.autocomplete.AutoCompletePopupWindow.setVisible(AutoCompletePopupWindow.java:734)
	at org.fife.ui.autocomplete.AutoCompletion.setPopupVisible(AutoCompletion.java:1146)
	at org.fife.ui.autocomplete.AutoCompletion.refreshPopupWindow(AutoCompletion.java:880)
	at org.fife.ui.autocomplete.AutoCompletion$AutoCompleteAction.actionPerformed(AutoCompletion.java:1426)
	at java.desktop/javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1810)
	at java.desktop/javax.swing.JComponent.processKeyBinding(JComponent.java:2947)
	at java.desktop/javax.swing.JComponent.processKeyBindings(JComponent.java:2995)
	at java.desktop/javax.swing.JComponent.processKeyEvent(JComponent.java:2909)
	at java.desktop/java.awt.Component.processEvent(Component.java:6403)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	.......
```
Hopefully this is something that I can fix on my end.

**Comment by MTrop** [comment]
Correction: this happened after I changed build parameters. D'oh. Easy fix. I hope.
